# Generated by Django 5.2.6 on 2026-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operational', 'Faol'), ('maintenance', 'Tamir'), ('degraded', 'Qisman faol')], default='operational', max_length=20, verbose_name='Tizim holati')),
                ('message', models.TextField(blank=True, help_text='Tizim holati haqida xabar', verbose_name='Xabar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Sistema sozlamalari',
                'verbose_name_plural': 'Sistema sozlamalari',
                'constraints': [models.UniqueConstraint(fields=('id',), name='single_system_settings')],
            },
        ),
    ]
