# Generated by Django 5.2.6 on 2026-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='used_at',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
