# Generated by Django 5.2.6 on 2026-04-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_student_learning_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['due_date', 'created_at'], 'verbose_name': 'Uy vazifasi', 'verbose_name_plural': 'Uy vazifalari'},
        ),
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Kutubxona elementi', 'verbose_name_plural': 'Kutubxona elementlari'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
    ]
