# Generated by Django 5.2.6 on 2026-04-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_homework_options_alter_libraryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='library/', verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl'),
        ),
    ]
