# Generated by Django 5.2.6 on 2026-04-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_libraryitem_file_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='file_url',
            new_name='video_url',
        ),
    ]
