# Generated by Django 5.2.6 on 2026-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_lesson_stream_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='twitch_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch Channel Name'),
        ),
    ]
