# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_lesson_twitch_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("finished", "Finished"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
