# Generated by Django 5.2.6 on 2026-04-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_lesson_status_video_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_url',
            field=models.URLField(blank=True, help_text='Ant Media HLS link, e.g. http://YOUR_IP:5080/LiveApp/streams/test_stream.m3u8', null=True, verbose_name='HLS Stream URL'),
        ),
    ]
