# Generated by Django 5.2.6 on 2026-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_lesson_hls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqti'),
        ),
    ]
